# Dockerfile for WhaleServer_Lite runing on tomcat 8.0.30-jre8
# 
# Version:0.1.0

FROM tomcat:8-jre8
MAINTAINER Zhouqiang <zhouqiang.wang@hotmail.com>

ADD WhaleServer.war /usr/local/tomcat/webapps/
